


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."audience_profiles" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "audience_asi_one_id" "text" NOT NULL,
    "personal_brand_agent_id" "text" NOT NULL,
    "name" "text",
    "role" "text",
    "contact" "text"
);


ALTER TABLE "public"."audience_profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."personal_brand_asi_one_relationships" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "personal_brand_agent_id" "text" NOT NULL,
    "asi_one_id" "text" NOT NULL
);


ALTER TABLE "public"."personal_brand_asi_one_relationships" OWNER TO "postgres";


ALTER TABLE "public"."personal_brand_asi_one_relationships" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."personal_brand_asi_one_relationships_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "asi_one_id" "text" NOT NULL,
    "name" "text"
);


ALTER TABLE "public"."user_profiles" OWNER TO "postgres";


ALTER TABLE "public"."user_profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_profile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."audience_profiles"
    ADD CONSTRAINT "audience_profiles_audience_asi_one_id_personal_brand_agent__key" UNIQUE ("audience_asi_one_id", "personal_brand_agent_id");



ALTER TABLE ONLY "public"."audience_profiles"
    ADD CONSTRAINT "audience_profiles_pkey" PRIMARY KEY ("audience_asi_one_id", "personal_brand_agent_id");



ALTER TABLE ONLY "public"."personal_brand_asi_one_relationships"
    ADD CONSTRAINT "personal_brand_asi_one_relationship_personal_brand_agent_id_key" UNIQUE ("personal_brand_agent_id");



ALTER TABLE ONLY "public"."personal_brand_asi_one_relationships"
    ADD CONSTRAINT "personal_brand_asi_one_relationships_asi_one_id_key" UNIQUE ("asi_one_id");



ALTER TABLE ONLY "public"."personal_brand_asi_one_relationships"
    ADD CONSTRAINT "personal_brand_asi_one_relationships_pkey" PRIMARY KEY ("id", "personal_brand_agent_id", "asi_one_id");



ALTER TABLE ONLY "public"."audience_profiles"
    ADD CONSTRAINT "unique_audience_personal_brand" UNIQUE ("audience_asi_one_id", "personal_brand_agent_id");



ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_asi_one_id_key" UNIQUE ("asi_one_id");



ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("id", "asi_one_id");



ALTER TABLE ONLY "public"."audience_profiles"
    ADD CONSTRAINT "audience_profiles_personal_brand_agent_id_fkey" FOREIGN KEY ("personal_brand_agent_id") REFERENCES "public"."personal_brand_asi_one_relationships"("personal_brand_agent_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."personal_brand_asi_one_relationships"
    ADD CONSTRAINT "personal_brand_asi_one_relationships_asi_one_id_fkey" FOREIGN KEY ("asi_one_id") REFERENCES "public"."user_profiles"("asi_one_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."audience_profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."personal_brand_asi_one_relationships" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_profiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."audience_profiles" TO "anon";
GRANT ALL ON TABLE "public"."audience_profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."audience_profiles" TO "service_role";



GRANT ALL ON TABLE "public"."personal_brand_asi_one_relationships" TO "anon";
GRANT ALL ON TABLE "public"."personal_brand_asi_one_relationships" TO "authenticated";
GRANT ALL ON TABLE "public"."personal_brand_asi_one_relationships" TO "service_role";



GRANT ALL ON SEQUENCE "public"."personal_brand_asi_one_relationships_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."personal_brand_asi_one_relationships_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."personal_brand_asi_one_relationships_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_profiles" TO "anon";
GRANT ALL ON TABLE "public"."user_profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_profile_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_profile_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_profile_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


